version: '3'

services:
  jellyfin:
    image: jellyfin/jellyfin
    ports:
      - '8096:8096'
    volumes:
      - './config:/config'
      - '/media:/media'
      - '/mnt/nas_data/videos:/videos'
    restart: always
